#!/usr/bin/env bash

bootstrap_path="$(cd "$(dirname "$0")" && pwd)"
source "$bootstrap_path/scripts/utility.sh"

install_packages() {
    if ! installed brew; then
        info_message "Installing Homebrew"
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        brew analytics off
    fi

    info_message "Installing software packages"
    brew bundle -v --no-lock --file="$bootstrap_path/scripts/Brewfile"
    brew cleanup
}

symlink() {
    local config_dir="$HOME/.config"
    mkdir -p "$config_dir"

    info_message "Symlinking files"
    link "$bootstrap_path/zsh/zshrc"        "$HOME/.zshrc"
    link "$bootstrap_path/zsh/zshenv"       "$HOME/.zshenv"
    link "$bootstrap_path/git/gitconfig"    "$HOME/.gitconfig"
    link "$bootstrap_path/tmux/tmux.conf"   "$HOME/.tmux.conf"
    link "$bootstrap_path/nvim"             "$config_dir/nvim"
}

system_settings() {
    info_message "Adjusting system settings"
    source "$bootstrap_path/scripts/mac-defaults.sh"
}

print_help() {
    printf "Usage: %s [options]\n" "$(basename "$0")"
    printf "Options:\n"
    printf "  -a,  --all                    Perform all actions\n"
    printf "  -h,  --help                   Display this help message\n"
    printf "  -l,  --link                   Generate symbolic links\n"
    printf "  -p,  --packages               Install software packages\n"
    printf "  -s,  --settings               Adjust system and application settings\n"
    exit 1
}

if [ "$#" -eq 0 ]; then
    printf "%s: " "$(basename "$0")"
    error_message "no flags were specified"
    print_help
else
    for flag in "$@"; do
        case $flag in
        -a|--all)
            install_packages
            symlink
            system_settings
            shift;;
        -h|--help)
            print_help
            shift;;
        -l|--link-files)
            symlink
            shift;;
        -p|--pacakges)
            install_packages
            shift;;
        -s|--settings)
            system_settings
            shift;;
        *)
            printf "%s: " "$(basename "$0")"
            error_message "invalid flag \'$flag\'"
            print_help
            shift;;
        esac
    done
fi
