export EDITOR="nvim"
export VISUAL=$EDITOR

export PATH="/opt/clangd/bin:$PATH"

if [[ "$OSTYPE" == "darwin"* ]]; then
    export LSCOLORS="ExGxFxdaCxDaDahbabacec"
    export HOMEBREW_AUTO_UPDATE_SECS=604800 # check for updates once a week
    export HOMEBREW_CLEANUP_MAX_AGE_DAYS=30
fi
