export zsh_config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export os_type=$(uname | tr '[:upper:]' '[:lower:]')

for file in "$zsh_config_dir"/*.zsh; do
    source "$file"
done
unset file

# load local settings
if [ -f "$HOME/.zshrc.local" ]; then
    source "$HOME/.zshrc.local"
fi
